### ISSUE TITLE
Bug: only first name of a split is displayed

### ISSUE THREAD

**Issue by BuistvoPloti** [EthanSK/restore-terminals-vscode#15]
While running the restore command, terminals appear with name but after all terminals are opened it shows only first name of each splitted area

VS Code version 1.57.1

https://i.imgur.com/90fcPJa.jpg

**Comment by MRVDH** [comment]
I'm running into the same issue.

**Comment by bandtank** [comment]
I briefly looked into this because I'm having the same problem, but I couldn't figure it out. The correct name is being passed to the `createNewSplitTerminal` function and this line of code executes as specified:

```
 90             if (name) {
 91                 yield vscode.commands.executeCommand("workbench.action.terminal.renameWithArg", {
 92                     name,
 93                 });
```

However, it is not clear to me if that is the right syntax for the `renameWithArg. I think the object needs to be `{"name": name}` instead of `{name}`, but it didn't work for me. [Here](https://github.com/microsoft/vscode/issues/128108) is where I first found that syntax.

**Comment by DannyChambers** [comment]
Love this plugin, and (my OCD) would also love to see this bug fixed 😄

**Comment by EthanSK** [comment]
@

> I briefly looked into this because I'm having the same problem, but I couldn't figure it out. The correct name is being passed to the `createNewSplitTerminal` function and this line of code executes as specified:
> 
> ```
>  90             if (name) {
>  91                 yield vscode.commands.executeCommand("workbench.action.terminal.renameWithArg", {
>  92                     name,
>  93                 });
> ```
> 
> However, it is not clear to me if that is the right syntax for the `renameWithArg`. I think the object needs to be `{"name": name}` instead of `{name}`, but it didn't work for me. [Here](https://github.com/microsoft/vscode/issues/128108) is where I first found that syntax.

those syntaxes are identical in JS
